In [1]:
import numpy as np

## Numpy Array initialization

In [12]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 3], [4, 5]])
print(f"array with 1d array {arr1}")
print(f"array with 2d array {arr2}")

# Array of Zeros
zeros = np.zeros((6, 5))
print("------------------Array of Zeros----------------")
print(zeros)

# Array of ones
ones = np.ones((6, 5))
print("------------------Array of Ones----------------")
print(ones)

# Array full of same values
fives =  np.full((6, 5), 5)
print("------------------Array of fives----------------")
print(fives)

# Array of values in a given range
values = np.arange(20) # you can slice with (stop, step, start)
print("------------------Array of values in range from (0-19) inclusive----------------")
print(values)

# Array of random integers
random_integers = np.random.randint(10, 1000, 8)
print("------------------Array of random  8 integers from to 10 100----------------")
print(random_integers)


------------------Array of Zeros----------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------Array of Ones----------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------Array of fives----------------
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
------------------Array of values in range from (0-19) inclusive----------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------------Array of random  8 integers from to 10 100----------------
[423 214 763 922 664 710 630 860]


## Numpy Array Stacking

In [19]:
# Vstack
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])
vstack_arr = np.vstack((arr1, arr2))
print("<-----------------Vertically stacked arrays-------------------------------->")
print(vstack_arr)

# Hstack
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])
hstack_arr = np.hstack((arr1, arr2))
print("<-----------------Horizontally stacked arrays-------------------------------->")
print(hstack_arr)

# ColumunStack Array
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])
column_arr = np.column_stack((arr1, arr2))
print("<-----------------Arrays stacked in a column---------------------------------------->")
print(column_arr)



<-----------------Vertically stacked arrays-------------------------------->
[[1 3 5]
 [2 4 6]]
<-----------------Horizontally stacked arrays-------------------------------->
[1 3 5 2 4 6]
<-----------------Arrays stacked in a column---------------------------------------->
[[1 2]
 [3 4]
 [5 6]]


## Numpy Array  Common Methods

### Numpy Array Intersection and Difference

In [50]:
# Numbers that are common in two array
arr1 = np.arange(1, 54, 3)
arr2 = np.arange(1, 90, 5)

intersect_arr = np.intersect1d(ar1=arr1, ar2=arr2)

print("<--------------------------------Array of numbers that are in both arr1 and arr2")
print(intersect_arr)

# Numbers that are unique in both arrays
set_arr = np.setdiff1d(ar1=arr1, ar2=arr2)
print("<--------------------------------Array of numbers that are only present in any of the two arrays")
print(set_arr)





<--------------------------------Array of numbers that are in both arr1 and arr2
[ 1 16 31 46]
<--------------------------------Array of numbers that are only present in any of the two arrays
[ 4  7 10 13 19 22 25 28 34 37 40 43 49 52]


### Numpy Array Math Methods

In [55]:
# Adding numbers row wise
sum_arr = np.sum((arr1, arr2), axis=0)
print(sum_arr)

# Adding numbers column wise
sum_arr = np.sum((arr1, arr2), axis=1)
print(sum_arr)

# Dot product of two arrays
dot_arr = np.dot(arr1, arr2)
print(dot_arr)

# Array division
average_arr = np.divide(arr1, arr2)
print(average_arr)

# Div mod array 
divmod_arr = np.divmod(arr1, arr2)
print(divmod_arr)

# Mean value
mean_value = np.mean(intersect_arr)
print(mean_value)

# Standard deviation
std_value = np.std(intersect_arr)
print(std_value)

# max, min
max_value = np.max(intersect_arr)
min_value = np.min(intersect_arr)
print(max_value)
print(min_value)





[  2  10  18  26  34  42  50  58  66  74  82  90  98 106 114 122 130 138]
[477 783]
28017
[1.         0.66666667 0.63636364 0.625      0.61904762 0.61538462
 0.61290323 0.61111111 0.6097561  0.60869565 0.60784314 0.60714286
 0.60655738 0.60606061 0.6056338  0.60526316 0.60493827 0.60465116]
(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([ 0,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52]))
23.5
16.77050983124842
46
1


### Numpy Array Saving and Loading

In [59]:
# Saving
arr = np.arange(100)
np.save('my_arr', arr)
print(arr)

# Loading a Numpy array
arr2 = np.load('my_arr.npy')
print(arr2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
